---
- name: Remove Bootstrap
  hosts: hosts
  become: yes

  tasks:
  - debug: 
      var: ansible_facts 

  - name: Remove apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: absent

  - name: Remove Grafana repo to sources list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: absent
      filename: grafana
      
  - name: Remove Grafana package
    ansible.builtin.apt:
      name: grafana
      state: absent