---
- name: Install Grafana
  hosts: hosts
  become: yes

  # testing locally first
  # already install pre-reqs when installing ansible
  tasks:
  - debug: 
      var: ansible_facts 

  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Add Grafana repo to sources list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      filename: grafana
  - name: Update apt cahce and install Grafana
    ansible.builtin.apt:
      update_cache: yes
      name: grafana
      state: present

  - name: Start and enable Grafana service
    ansible.builtin.systemd_service:
      state: started
      name: grafana-server
      enabled: true